__include__: [
  '../dataset/custom_detection.yml',
  '../runtime.yml',
  '../base/dataloader_dfine.yml',
  '../base/optimizer.yml',
  '../base/dfine_hgnetv2.yml',
  '../base/common.yml'
]

comment: 'WaveEncoderBlock, s'

output_dir: ./outputs/my1_wave_s

DEIM_MG:
  yaml_path: configs/cfg/my1_wave_s.yaml
# Increase to search for the optimal ema
epoches: 72
train_dataloader:
  dataset:
    transforms:
      policy:
        epoch: 60
  collate_fn:
    stop_epoch: 60
    ema_restart_decay: 0.9999
    base_size_repeat: ~
