task: detection

evaluator: # 指标
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 1 # your dataset classes
remap_mscoco_category: True

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: data/gwhd_2021/train/images
    ann_file: data/gwhd_2021/annotations/train.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 4
  drop_last: True
  pin_memory: False
  collate_fn:
    type: BatchImageCollateFunction



# validation dataloader
# val_dataloader:
#   type: DataLoader
#   dataset:
#     type: CocoDetection
#     img_folder: data/gwhd_2021/val/images
#     ann_file: data/gwhd_2021/annotations/val.json

#     return_masks: False
#     transforms:
#       type: Compose
#       ops: ~
#   shuffle: False
#   num_workers: 4
#   drop_last: False
#   pin_memory: False
#   collate_fn:
#     type: BatchImageCollateFunction

# test dataloader
val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: data/gwhd_2021/test_domain/data/ARC_1
    ann_file: data/gwhd_2021/test_domain/annotations/ARC_1_annotations.json

    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 4
  drop_last: False
  pin_memory: False
  collate_fn:
    type: BatchImageCollateFunction



